// src/components/integrations/solid/GlassButton.tsx
import { Dynamic } from "solid-js/web";
import { useStore } from "@/_global/piquo";
import { propsClass } from "@/_global/lib/utils";
import type { JSX } from "solid-js";
import type { DeepGuard } from "@/_global/types/types";
import "@/components/shared/Sections/Glass.sass";

type Props = {
	children: JSX.Element;
} & ( | (JSX.IntrinsicElements['a'] & {
	as: 'a';
	href: string;
}) | (JSX.IntrinsicElements['div'] & {
	as: 'div';
	href?: never;
}));

export default function GlassButton(props: DeepGuard<Props>) {
	const { navOpened, setNavOpened } = useStore('navOpened');

	const handleClick = (e?: Event) => {
		if (e) {
			e.preventDefault();
			setNavOpened(!navOpened());
		} else {
			setNavOpened(false);
		}
	};

	return (
		<Dynamic component={ props.as } { ...props } onClick={ (e: Event) => handleClick(props.as === 'a' ? undefined : e) } class="glass mini is_dark" classList={{ ...propsClass(props) }}>
			{ props.children }
		</Dynamic>
	)
}

// src/components/integrations/vue/GlassButton.vue
<script setup lang="ts">
	import { useStore } from "@/_global/piquo";
	import type { JSX } from "vue/jsx-runtime";
	import "@/components/shared/Sections/Glass.sass";

	type Props = ( | (/* @vue-ignore */ JSX.IntrinsicElements['a'] & {
		as: 'a';
		href: string;
		target?: '_blank';
	}) | (/* @vue-ignore */ JSX.IntrinsicElements['div'] & {
		as: 'div';
		href?: never;
	}));

	const props = defineProps<Props>();

	const { navOpened, setNavOpened } = useStore('navOpened');

	const handleClick = (e?: Event) => {
		if (e) {
			e.preventDefault();
			setNavOpened(!navOpened());
		} else {
			setNavOpened(false);
		}
	};
</script>
<template>
	<a v-if="props.as === 'a'" v-bind="props" @click="() => handleClick()" :class="[ 'glass mini is_dark', props.class ]">
		<slot />
	</a>
	<div v-else v-bind="props" @click="handleClick" :class="[ 'glass mini is_dark', props.class ]">
		<slot />
	</div>
</template>
